/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gregorlogik;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author markus
 */
public class NewJFrame extends javax.swing.JFrame implements Runnable {

    private boolean fileChoosen;
    private GregorLogik gregLogik;
    private String absolutePathCSV;
    private boolean run;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.fileChoosen = false;
        this.gregLogik = new GregorLogik();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV", "csv");
        this.fileChooser.setFileFilter(filter);
        this.fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fileChooser = new JFileChooser();
        labelCsvPath = new JLabel();
        openFileButton = new JButton();
        jScrollPane1 = new JScrollPane();
        output = new JTextArea();
        showPath = new JLabel();
        suggestions = new JButton();
        error = new JLabel();

        fileChooser.setDialogTitle("This is my open dialog");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lagerausgleich");
        addComponentListener(new ComponentAdapter()
        {
            public void componentResized(ComponentEvent evt)
            {
                formComponentResized(evt);
            }
        });

        labelCsvPath.setText("CSV- Pfad:");
        labelCsvPath.setToolTipText("");

        openFileButton.setText("Datei öffnen");
        openFileButton.setActionCommand("openFile");
        openFileButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                openFileButtonActionPerformed(evt);
            }
        });

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        suggestions.setText("Empfehlungen");
        suggestions.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                suggestionsActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(error, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(suggestions))
                    .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelCsvPath)
                        .addGap(18, 18, 18)
                        .addComponent(showPath, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(openFileButton)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCsvPath)
                    .addComponent(openFileButton)
                    .addComponent(showPath))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestions)
                    .addComponent(error))
                .addGap(12, 12, 12))
        );

        getAccessibleContext().setAccessibleName("Lagerausgleich");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            this.absolutePathCSV = file.getAbsolutePath();

            this.showPath.setText(
                    this.absolutePathCSV);

            this.pack();
            this.fileChoosen = true;
            this.output.setText("");
            this.error.setText("");
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    public void setResult(String result) {
        this.run = false;
         this.error.setText("Fertig!");
        this.output.setText(result);
    }

    @Override
    public void run() {

        while (this.run) {
            try {
                if(this.run)
                this.error.setText("rechnet");
                Thread.sleep(1000);
                if(this.run)
                this.error.setText("rechnet.");
                Thread.sleep(1000);
                if(this.run)
                this.error.setText("rechnet..");
                Thread.sleep(1000);
                if(this.run)
                this.error.setText("rechnet...");
                Thread.sleep(1000);
            } catch (Exception e) {
            }

           
        }
    }

    private void suggestionsActionPerformed(ActionEvent evt)//GEN-FIRST:event_suggestionsActionPerformed
    {//GEN-HEADEREND:event_suggestionsActionPerformed
        if (this.fileChoosen) {
            this.output.setText("");
            this.gregLogik.setPath(this.showPath.getText(), this);
            new Thread(this.gregLogik).start();
            this.run = true;
            new Thread(this).start();

        } else {
            this.error.setText("Es wurde keine Datei ausgewählt!");
        }

    }//GEN-LAST:event_suggestionsActionPerformed

    private void formComponentResized(ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized


    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments ////
     */
    public static void main(String args[]) {
        /* Set the Dracula look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dracula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel error;
    private JFileChooser fileChooser;
    private JScrollPane jScrollPane1;
    private JLabel labelCsvPath;
    private JButton openFileButton;
    private JTextArea output;
    private JLabel showPath;
    private JButton suggestions;
    // End of variables declaration//GEN-END:variables

}
